# Parameters for Travis CI tests
# These are automated tests that run after each commit
# see: https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  # install dependencies
  - pip install llvmlite --prefer-binary
  - pip install -r requirements.txt
  - pip install .
  # install testing dependencies
  - pip install pytest>=3.0
  - pip install pytest-cov==2.5.0
  - pip install python-coveralls
  # install documentation dependencies
  - pip install sphinx>=1.6
  - pip install sphinx_rtd_theme
script: 
  # run tests
  - py.test ./tests/ --verbose --doctest-modules --color=yes --cov=./qmix/ --cov-report=term-missing
  # build documentation
  - ln -s notebooks/*.ipynb docs/source/
  - make -C docs/ html
  - touch docs/build/html/.nojekyll
after_success:
  # for coveralls.io
  - coveralls
deploy:
  # push to github pages
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/build/html/
    keep_history: true