name: qmix
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.5
  - pip
  # QMix dependencies (same as requirements.txt)
  - matplotlib
  - numba
  - numpy
  - scipy
  # for generating documentation
  - ipython
  - ipykernel
  - jupyter
  - nbconvert
  - nb_conda
  - pandoc
  - sphinx>=1.6
  - sphinx_rtd_theme
  - pip:
    - nbsphinx
    - tornado==4.5.3
  # for testing
  - pytest>=3.0
  - pip:
    - pytest-cov==2.5.0
    - python-coveralls
